---
title: Education
---

## PhD in Advanced Spatial Analysis  
**March 2022 - Present**  
<a href="https://www.ucl.ac.uk/bartlett/casa/study/advanced-spatial-analysis-mphilphd" target="_blank">Centre for Advanced Spatial Analysis (CASA)</a> | <a href="https://www.ucl.ac.uk/bartlett/" target="_blank">The Bartlett Faculty of the Built Environment</a> | <a href="https://www.ucl.ac.uk/" target="_blank">University College London</a>

**Research Topic**:  
*Quantifying digital injustice: a case study of Nairobi, Kenya*

**Research Plan**:  
Developing a workflow to assess the performance of big data by comparing it with traditional methods in Nairobi, Kenya; identifying digitally invisible groups and proposing mitigation approaches to empower these groups for data-enabled decision-making.

---

## MSc in Environmental Technology  
**September 2019 - September 2020**  
<a href="https://www.imperial.ac.uk/environmental-policy/" target="_blank">Centre for Environmental Policy</a> | <a href="https://www.imperial.ac.uk/natural-sciences/" target="_blank">Faculty of Natural Sciences</a> | <a href="https://www.imperial.ac.uk/" target="_blank">Imperial College London</a>

**Master Thesis**:  
*Distributed Ledger Technology enabled passenger control system to maintain social distancing on public transport during COVID-19*

**Result & Outcome**:  
Applied a resource-sharing algorithm to the public transport sector to control passenger movement. The system, enhanced by distributed ledger technology, used smart card data from the London Underground to simulate and enforce compliance.

---

## BEng in Marine Resource Development Technology  
**September 2015 - June 2019**  
<a href="https://mc.wh.sdu.edu.cn/" target="_blank">Marine College</a> | <a href="https://www.en.sdu.edu.cn/" target="_blank">Shandong University</a>  
<a href="https://mc.wh.sdu.edu.cn/" target="_blank">海洋学院</a> | <a href="https://www.sdu.edu.cn/" target="_blank">山东大学</a>

**Bachelor Thesis**:  
*An Anoxic Bio-Filter (ABF) - Membrane Bioreactor (MBR) combined process on high salinity wastewater treatment and the effect of membrane fouling*

**Result & Outcome**:  
Designed and installed an ABF system to enhance the existing MBR setup; conducted rigorous testing to evaluate the combined ABF-MBR process's efficiency in denitrification and membrane fouling reduction; produced a comprehensive report detailing findings and recommendations.

